using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VeilleNet.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddNamedEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS containsharp.named_entities (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name character varying(200) NOT NULL,
                created_at timestamp with time zone NOT NULL
            );

            CREATE TABLE IF NOT EXISTS containsharp.article_entities (
                article_id integer NOT NULL,
                entity_id integer NOT NULL,
                CONSTRAINT PK_article_entities PRIMARY KEY (article_id, entity_id),
                CONSTRAINT FK_article_entities_named_entities_entity_id
                    FOREIGN KEY (entity_id)
                    REFERENCES containsharp.named_entities (id)
                    ON DELETE CASCADE,
                CONSTRAINT FK_article_entities_news_articles_article_id
                    FOREIGN KEY (article_id)
                    REFERENCES containsharp.news_articles (id)
                    ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS IX_named_entities_name
                ON containsharp.named_entities (name);

            CREATE INDEX IF NOT EXISTS IX_article_entities_entity_id
                ON containsharp.article_entities (entity_id);
        ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        migrationBuilder.Sql(@"
            DROP TABLE IF EXISTS containsharp.article_entities;
            DROP TABLE IF EXISTS containsharp.named_entities;
        ");
        }
    }
}
